/********************************************************************************
** Form generated from reading UI file 'wizardui.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WIZARDUI_H
#define UI_WIZARDUI_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_WizardUI
{
public:
    QAction *actionExit;
    QAction *actionSave;
    QAction *actionLoad;
    QWidget *centralWidget;
    QGroupBox *groupBox;
    QCheckBox *checkBox_32;
    QCheckBox *checkBox_19;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox_18;
    QCheckBox *checkBox_8;
    QCheckBox *checkBox_21;
    QCheckBox *checkBox_16;
    QCheckBox *checkBox_14;
    QCheckBox *checkBox_9;
    QCheckBox *checkBox_15;
    QCheckBox *checkBox_11;
    QCheckBox *checkBox_17;
    QCheckBox *checkBox_2;
    QCheckBox *checkBox_10;
    QCheckBox *checkBox_12;
    QCheckBox *checkBox_7;
    QCheckBox *checkBox_25;
    QCheckBox *checkBox_3;
    QCheckBox *checkBox_13;
    QCheckBox *checkBox;
    QCheckBox *checkBox_6;
    QCheckBox *checkBox_22;
    QCheckBox *checkBox_20;
    QCheckBox *checkBox_30;
    QGroupBox *groupBox_2;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLabel *label_3;
    QLabel *label_4;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLabel *label_5;
    QLineEdit *lineEdit_6;
    QLabel *label_6;
    QLineEdit *lineEdit_7;
    QLabel *label_7;
    QLineEdit *lineEdit_8;
    QLineEdit *lineEdit_9;
    QLabel *label_8;
    QLineEdit *lineEdit_10;
    QLabel *label_9;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QPushButton *pushButton_15;
    QPushButton *pushButton_16;
    QLineEdit *lineEdit_59;
    QLabel *label_10;
    QLabel *label_11;
    QLineEdit *lineEdit_60;
    QLabel *label_12;
    QLineEdit *lineEdit_62;
    QPushButton *pushButton_65;
    QPushButton *pushButton_66;
    QLineEdit *lineEdit_63;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *lineEdit_61;
    QLineEdit *lineEdit_64;
    QLabel *label_15;
    QPushButton *pushButton_37;
    QGroupBox *groupBox_3;
    QLineEdit *lineEdit_11;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QLineEdit *lineEdit_12;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QLineEdit *lineEdit_15;
    QLineEdit *lineEdit_16;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_18;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QLineEdit *lineEdit_21;
    QLineEdit *lineEdit_22;
    QPushButton *pushButton_36;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QPushButton *pushButton_41;
    QPushButton *pushButton_6;
    QLineEdit *lineEdit_13;
    QLineEdit *lineEdit_14;
    QPushButton *pushButton_5;
    QPushButton *pushButton_35;
    QPushButton *pushButton_42;
    QGroupBox *groupBox_4;
    QCheckBox *checkBox_5;
    QLineEdit *lineEdit_23;
    QCheckBox *checkBox_23;
    QLineEdit *lineEdit_24;
    QCheckBox *checkBox_24;
    QCheckBox *checkBox_26;
    QLineEdit *lineEdit_25;
    QLineEdit *lineEdit_26;
    QCheckBox *checkBox_27;
    QCheckBox *checkBox_28;
    QLineEdit *lineEdit_27;
    QLineEdit *lineEdit_28;
    QLineEdit *lineEdit_29;
    QLineEdit *lineEdit_30;
    QLineEdit *lineEdit_31;
    QCheckBox *checkBox_29;
    QLineEdit *lineEdit_32;
    QCheckBox *checkBox_31;
    QCheckBox *checkBox_33;
    QCheckBox *checkBox_34;
    QCheckBox *checkBox_35;
    QCheckBox *checkBox_36;
    QLineEdit *lineEdit_33;
    QLineEdit *lineEdit_34;
    QLineEdit *lineEdit_36;
    QLineEdit *lineEdit_37;
    QLineEdit *lineEdit_38;
    QLineEdit *lineEdit_39;
    QCheckBox *checkBox_38;
    QCheckBox *checkBox_39;
    QCheckBox *checkBox_40;
    QLineEdit *lineEdit_41;
    QCheckBox *checkBox_41;
    QCheckBox *checkBox_42;
    QCheckBox *checkBox_44;
    QLineEdit *lineEdit_42;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QGroupBox *groupBox_5;
    QCheckBox *checkBox_37;
    QLineEdit *lineEdit_53;
    QCheckBox *checkBox_43;
    QLineEdit *lineEdit_54;
    QCheckBox *checkBox_45;
    QCheckBox *checkBox_46;
    QLineEdit *lineEdit_55;
    QLineEdit *lineEdit_56;
    QCheckBox *checkBox_47;
    QCheckBox *checkBox_48;
    QLineEdit *lineEdit_57;
    QLineEdit *lineEdit_58;
    QPushButton *pushButton_59;
    QPushButton *pushButton_60;
    QPushButton *pushButton_61;
    QPushButton *pushButton_62;
    QPushButton *pushButton_63;
    QPushButton *pushButton_64;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *WizardUI)
    {
        if (WizardUI->objectName().isEmpty())
            WizardUI->setObjectName(QStringLiteral("WizardUI"));
        WizardUI->resize(1093, 765);
        actionExit = new QAction(WizardUI);
        actionExit->setObjectName(QStringLiteral("actionExit"));
        actionSave = new QAction(WizardUI);
        actionSave->setObjectName(QStringLiteral("actionSave"));
        actionLoad = new QAction(WizardUI);
        actionLoad->setObjectName(QStringLiteral("actionLoad"));
        centralWidget = new QWidget(WizardUI);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(650, 20, 321, 101));
        checkBox_32 = new QCheckBox(groupBox);
        checkBox_32->setObjectName(QStringLiteral("checkBox_32"));
        checkBox_32->setEnabled(false);
        checkBox_32->setGeometry(QRect(190, 40, 31, 17));
        checkBox_19 = new QCheckBox(groupBox);
        checkBox_19->setObjectName(QStringLiteral("checkBox_19"));
        checkBox_19->setEnabled(false);
        checkBox_19->setGeometry(QRect(130, 40, 31, 17));
        checkBox_4 = new QCheckBox(groupBox);
        checkBox_4->setObjectName(QStringLiteral("checkBox_4"));
        checkBox_4->setEnabled(true);
        checkBox_4->setGeometry(QRect(10, 40, 31, 17));
        checkBox_18 = new QCheckBox(groupBox);
        checkBox_18->setObjectName(QStringLiteral("checkBox_18"));
        checkBox_18->setEnabled(false);
        checkBox_18->setGeometry(QRect(130, 60, 31, 17));
        checkBox_18->setAutoExclusive(false);
        checkBox_8 = new QCheckBox(groupBox);
        checkBox_8->setObjectName(QStringLiteral("checkBox_8"));
        checkBox_8->setEnabled(true);
        checkBox_8->setGeometry(QRect(40, 20, 31, 17));
        checkBox_21 = new QCheckBox(groupBox);
        checkBox_21->setObjectName(QStringLiteral("checkBox_21"));
        checkBox_21->setEnabled(false);
        checkBox_21->setGeometry(QRect(280, 20, 31, 17));
        checkBox_16 = new QCheckBox(groupBox);
        checkBox_16->setObjectName(QStringLiteral("checkBox_16"));
        checkBox_16->setEnabled(false);
        checkBox_16->setGeometry(QRect(100, 20, 31, 17));
        checkBox_14 = new QCheckBox(groupBox);
        checkBox_14->setObjectName(QStringLiteral("checkBox_14"));
        checkBox_14->setEnabled(false);
        checkBox_14->setGeometry(QRect(100, 60, 31, 17));
        checkBox_9 = new QCheckBox(groupBox);
        checkBox_9->setObjectName(QStringLiteral("checkBox_9"));
        checkBox_9->setEnabled(false);
        checkBox_9->setGeometry(QRect(190, 20, 31, 17));
        checkBox_15 = new QCheckBox(groupBox);
        checkBox_15->setObjectName(QStringLiteral("checkBox_15"));
        checkBox_15->setEnabled(false);
        checkBox_15->setGeometry(QRect(100, 40, 31, 17));
        checkBox_11 = new QCheckBox(groupBox);
        checkBox_11->setObjectName(QStringLiteral("checkBox_11"));
        checkBox_11->setEnabled(false);
        checkBox_11->setGeometry(QRect(70, 40, 31, 17));
        checkBox_17 = new QCheckBox(groupBox);
        checkBox_17->setObjectName(QStringLiteral("checkBox_17"));
        checkBox_17->setEnabled(false);
        checkBox_17->setGeometry(QRect(220, 20, 31, 17));
        checkBox_2 = new QCheckBox(groupBox);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setEnabled(true);
        checkBox_2->setGeometry(QRect(10, 60, 31, 17));
        checkBox_10 = new QCheckBox(groupBox);
        checkBox_10->setObjectName(QStringLiteral("checkBox_10"));
        checkBox_10->setEnabled(false);
        checkBox_10->setGeometry(QRect(70, 60, 31, 17));
        checkBox_12 = new QCheckBox(groupBox);
        checkBox_12->setObjectName(QStringLiteral("checkBox_12"));
        checkBox_12->setEnabled(false);
        checkBox_12->setGeometry(QRect(70, 20, 31, 17));
        checkBox_7 = new QCheckBox(groupBox);
        checkBox_7->setObjectName(QStringLiteral("checkBox_7"));
        checkBox_7->setEnabled(true);
        checkBox_7->setGeometry(QRect(40, 40, 31, 17));
        checkBox_25 = new QCheckBox(groupBox);
        checkBox_25->setObjectName(QStringLiteral("checkBox_25"));
        checkBox_25->setEnabled(false);
        checkBox_25->setGeometry(QRect(160, 40, 31, 17));
        checkBox_3 = new QCheckBox(groupBox);
        checkBox_3->setObjectName(QStringLiteral("checkBox_3"));
        checkBox_3->setEnabled(true);
        checkBox_3->setGeometry(QRect(10, 80, 31, 17));
        checkBox_13 = new QCheckBox(groupBox);
        checkBox_13->setObjectName(QStringLiteral("checkBox_13"));
        checkBox_13->setEnabled(false);
        checkBox_13->setGeometry(QRect(220, 40, 31, 17));
        checkBox = new QCheckBox(groupBox);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setEnabled(true);
        checkBox->setGeometry(QRect(10, 20, 31, 17));
        checkBox_6 = new QCheckBox(groupBox);
        checkBox_6->setObjectName(QStringLiteral("checkBox_6"));
        checkBox_6->setEnabled(true);
        checkBox_6->setGeometry(QRect(40, 60, 31, 17));
        checkBox_22 = new QCheckBox(groupBox);
        checkBox_22->setObjectName(QStringLiteral("checkBox_22"));
        checkBox_22->setEnabled(false);
        checkBox_22->setGeometry(QRect(250, 20, 31, 17));
        checkBox_20 = new QCheckBox(groupBox);
        checkBox_20->setObjectName(QStringLiteral("checkBox_20"));
        checkBox_20->setEnabled(false);
        checkBox_20->setGeometry(QRect(130, 20, 31, 17));
        checkBox_30 = new QCheckBox(groupBox);
        checkBox_30->setObjectName(QStringLiteral("checkBox_30"));
        checkBox_30->setEnabled(false);
        checkBox_30->setGeometry(QRect(160, 20, 31, 17));
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 20, 321, 391));
        label = new QLabel(groupBox_2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(20, 80, 46, 21));
        label_2 = new QLabel(groupBox_2);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(20, 110, 46, 21));
        lineEdit_2 = new QLineEdit(groupBox_2);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(50, 110, 101, 20));
        lineEdit_3 = new QLineEdit(groupBox_2);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setEnabled(false);
        lineEdit_3->setGeometry(QRect(50, 80, 41, 20));
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(140, 80, 61, 21));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(160, 110, 31, 21));
        lineEdit_4 = new QLineEdit(groupBox_2);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(200, 80, 111, 20));
        lineEdit_5 = new QLineEdit(groupBox_2);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(190, 110, 121, 20));
        label_5 = new QLabel(groupBox_2);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(20, 50, 81, 21));
        lineEdit_6 = new QLineEdit(groupBox_2);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(100, 50, 211, 20));
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(20, 20, 61, 21));
        lineEdit_7 = new QLineEdit(groupBox_2);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(90, 20, 221, 20));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(20, 140, 46, 21));
        lineEdit_8 = new QLineEdit(groupBox_2);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setEnabled(false);
        lineEdit_8->setGeometry(QRect(39, 170, 81, 20));
        lineEdit_9 = new QLineEdit(groupBox_2);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(70, 140, 131, 20));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(20, 170, 20, 21));
        lineEdit_10 = new QLineEdit(groupBox_2);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(190, 170, 81, 20));
        label_9 = new QLabel(groupBox_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(130, 170, 61, 21));
        pushButton = new QPushButton(groupBox_2);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(270, 170, 21, 23));
        pushButton_2 = new QPushButton(groupBox_2);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(290, 170, 21, 23));
        pushButton_15 = new QPushButton(groupBox_2);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(110, 80, 21, 23));
        pushButton_16 = new QPushButton(groupBox_2);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(90, 80, 21, 23));
        lineEdit_59 = new QLineEdit(groupBox_2);
        lineEdit_59->setObjectName(QStringLiteral("lineEdit_59"));
        lineEdit_59->setGeometry(QRect(100, 200, 31, 20));
        label_10 = new QLabel(groupBox_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 200, 91, 21));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(140, 200, 61, 21));
        lineEdit_60 = new QLineEdit(groupBox_2);
        lineEdit_60->setObjectName(QStringLiteral("lineEdit_60"));
        lineEdit_60->setGeometry(QRect(200, 200, 31, 20));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 230, 71, 21));
        lineEdit_62 = new QLineEdit(groupBox_2);
        lineEdit_62->setObjectName(QStringLiteral("lineEdit_62"));
        lineEdit_62->setEnabled(false);
        lineEdit_62->setGeometry(QRect(70, 230, 41, 20));
        pushButton_65 = new QPushButton(groupBox_2);
        pushButton_65->setObjectName(QStringLiteral("pushButton_65"));
        pushButton_65->setGeometry(QRect(290, 230, 21, 23));
        pushButton_66 = new QPushButton(groupBox_2);
        pushButton_66->setObjectName(QStringLiteral("pushButton_66"));
        pushButton_66->setGeometry(QRect(270, 230, 21, 23));
        lineEdit_63 = new QLineEdit(groupBox_2);
        lineEdit_63->setObjectName(QStringLiteral("lineEdit_63"));
        lineEdit_63->setEnabled(true);
        lineEdit_63->setGeometry(QRect(230, 230, 41, 20));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(120, 230, 111, 21));
        label_14 = new QLabel(groupBox_2);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(10, 260, 46, 21));
        lineEdit_61 = new QLineEdit(groupBox_2);
        lineEdit_61->setObjectName(QStringLiteral("lineEdit_61"));
        lineEdit_61->setGeometry(QRect(160, 260, 51, 20));
        lineEdit_64 = new QLineEdit(groupBox_2);
        lineEdit_64->setObjectName(QStringLiteral("lineEdit_64"));
        lineEdit_64->setGeometry(QRect(60, 260, 51, 20));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(120, 260, 41, 21));
        pushButton_37 = new QPushButton(groupBox_2);
        pushButton_37->setObjectName(QStringLiteral("pushButton_37"));
        pushButton_37->setGeometry(QRect(230, 260, 75, 23));
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(490, 180, 231, 191));
        lineEdit_11 = new QLineEdit(groupBox_3);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(100, 20, 41, 20));
        pushButton_3 = new QPushButton(groupBox_3);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(160, 20, 21, 23));
        pushButton_4 = new QPushButton(groupBox_3);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(140, 20, 21, 23));
        lineEdit_12 = new QLineEdit(groupBox_3);
        lineEdit_12->setObjectName(QStringLiteral("lineEdit_12"));
        lineEdit_12->setEnabled(false);
        lineEdit_12->setGeometry(QRect(180, 20, 31, 20));
        pushButton_7 = new QPushButton(groupBox_3);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(160, 60, 21, 23));
        pushButton_8 = new QPushButton(groupBox_3);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(140, 60, 21, 23));
        lineEdit_15 = new QLineEdit(groupBox_3);
        lineEdit_15->setObjectName(QStringLiteral("lineEdit_15"));
        lineEdit_15->setEnabled(false);
        lineEdit_15->setGeometry(QRect(180, 60, 31, 20));
        lineEdit_16 = new QLineEdit(groupBox_3);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(100, 60, 41, 20));
        pushButton_9 = new QPushButton(groupBox_3);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(160, 80, 21, 23));
        pushButton_10 = new QPushButton(groupBox_3);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(140, 80, 21, 23));
        lineEdit_17 = new QLineEdit(groupBox_3);
        lineEdit_17->setObjectName(QStringLiteral("lineEdit_17"));
        lineEdit_17->setEnabled(false);
        lineEdit_17->setGeometry(QRect(180, 80, 31, 20));
        lineEdit_18 = new QLineEdit(groupBox_3);
        lineEdit_18->setObjectName(QStringLiteral("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(100, 80, 41, 20));
        pushButton_11 = new QPushButton(groupBox_3);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(160, 100, 21, 23));
        pushButton_12 = new QPushButton(groupBox_3);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(140, 100, 21, 23));
        lineEdit_19 = new QLineEdit(groupBox_3);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setEnabled(false);
        lineEdit_19->setGeometry(QRect(180, 100, 31, 20));
        lineEdit_20 = new QLineEdit(groupBox_3);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(100, 100, 41, 20));
        pushButton_13 = new QPushButton(groupBox_3);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(160, 120, 21, 23));
        pushButton_14 = new QPushButton(groupBox_3);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(140, 120, 21, 23));
        lineEdit_21 = new QLineEdit(groupBox_3);
        lineEdit_21->setObjectName(QStringLiteral("lineEdit_21"));
        lineEdit_21->setEnabled(false);
        lineEdit_21->setGeometry(QRect(180, 120, 31, 20));
        lineEdit_22 = new QLineEdit(groupBox_3);
        lineEdit_22->setObjectName(QStringLiteral("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(100, 120, 41, 20));
        pushButton_36 = new QPushButton(groupBox_3);
        pushButton_36->setObjectName(QStringLiteral("pushButton_36"));
        pushButton_36->setGeometry(QRect(10, 80, 91, 23));
        pushButton_38 = new QPushButton(groupBox_3);
        pushButton_38->setObjectName(QStringLiteral("pushButton_38"));
        pushButton_38->setGeometry(QRect(10, 100, 91, 23));
        pushButton_39 = new QPushButton(groupBox_3);
        pushButton_39->setObjectName(QStringLiteral("pushButton_39"));
        pushButton_39->setGeometry(QRect(10, 40, 91, 23));
        pushButton_40 = new QPushButton(groupBox_3);
        pushButton_40->setObjectName(QStringLiteral("pushButton_40"));
        pushButton_40->setGeometry(QRect(10, 60, 91, 23));
        pushButton_41 = new QPushButton(groupBox_3);
        pushButton_41->setObjectName(QStringLiteral("pushButton_41"));
        pushButton_41->setGeometry(QRect(10, 120, 91, 23));
        pushButton_6 = new QPushButton(groupBox_3);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(140, 40, 21, 23));
        lineEdit_13 = new QLineEdit(groupBox_3);
        lineEdit_13->setObjectName(QStringLiteral("lineEdit_13"));
        lineEdit_13->setEnabled(false);
        lineEdit_13->setGeometry(QRect(180, 40, 31, 20));
        lineEdit_14 = new QLineEdit(groupBox_3);
        lineEdit_14->setObjectName(QStringLiteral("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(100, 40, 41, 20));
        pushButton_5 = new QPushButton(groupBox_3);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(160, 40, 21, 23));
        pushButton_35 = new QPushButton(groupBox_3);
        pushButton_35->setObjectName(QStringLiteral("pushButton_35"));
        pushButton_35->setGeometry(QRect(10, 20, 91, 23));
        pushButton_42 = new QPushButton(groupBox_3);
        pushButton_42->setObjectName(QStringLiteral("pushButton_42"));
        pushButton_42->setGeometry(QRect(140, 150, 75, 23));
        groupBox_4 = new QGroupBox(centralWidget);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(330, 20, 161, 391));
        checkBox_5 = new QCheckBox(groupBox_4);
        checkBox_5->setObjectName(QStringLiteral("checkBox_5"));
        checkBox_5->setGeometry(QRect(10, 20, 21, 21));
        lineEdit_23 = new QLineEdit(groupBox_4);
        lineEdit_23->setObjectName(QStringLiteral("lineEdit_23"));
        lineEdit_23->setEnabled(false);
        lineEdit_23->setGeometry(QRect(30, 20, 31, 20));
        checkBox_23 = new QCheckBox(groupBox_4);
        checkBox_23->setObjectName(QStringLiteral("checkBox_23"));
        checkBox_23->setGeometry(QRect(10, 40, 21, 21));
        lineEdit_24 = new QLineEdit(groupBox_4);
        lineEdit_24->setObjectName(QStringLiteral("lineEdit_24"));
        lineEdit_24->setEnabled(false);
        lineEdit_24->setGeometry(QRect(30, 40, 31, 20));
        checkBox_24 = new QCheckBox(groupBox_4);
        checkBox_24->setObjectName(QStringLiteral("checkBox_24"));
        checkBox_24->setGeometry(QRect(10, 80, 21, 21));
        checkBox_26 = new QCheckBox(groupBox_4);
        checkBox_26->setObjectName(QStringLiteral("checkBox_26"));
        checkBox_26->setGeometry(QRect(10, 60, 21, 21));
        lineEdit_25 = new QLineEdit(groupBox_4);
        lineEdit_25->setObjectName(QStringLiteral("lineEdit_25"));
        lineEdit_25->setEnabled(false);
        lineEdit_25->setGeometry(QRect(30, 60, 31, 20));
        lineEdit_26 = new QLineEdit(groupBox_4);
        lineEdit_26->setObjectName(QStringLiteral("lineEdit_26"));
        lineEdit_26->setEnabled(false);
        lineEdit_26->setGeometry(QRect(30, 80, 31, 20));
        checkBox_27 = new QCheckBox(groupBox_4);
        checkBox_27->setObjectName(QStringLiteral("checkBox_27"));
        checkBox_27->setGeometry(QRect(10, 120, 21, 21));
        checkBox_28 = new QCheckBox(groupBox_4);
        checkBox_28->setObjectName(QStringLiteral("checkBox_28"));
        checkBox_28->setGeometry(QRect(10, 100, 21, 21));
        lineEdit_27 = new QLineEdit(groupBox_4);
        lineEdit_27->setObjectName(QStringLiteral("lineEdit_27"));
        lineEdit_27->setEnabled(false);
        lineEdit_27->setGeometry(QRect(30, 100, 31, 20));
        lineEdit_28 = new QLineEdit(groupBox_4);
        lineEdit_28->setObjectName(QStringLiteral("lineEdit_28"));
        lineEdit_28->setEnabled(false);
        lineEdit_28->setGeometry(QRect(30, 120, 31, 20));
        lineEdit_29 = new QLineEdit(groupBox_4);
        lineEdit_29->setObjectName(QStringLiteral("lineEdit_29"));
        lineEdit_29->setEnabled(false);
        lineEdit_29->setGeometry(QRect(30, 220, 31, 20));
        lineEdit_30 = new QLineEdit(groupBox_4);
        lineEdit_30->setObjectName(QStringLiteral("lineEdit_30"));
        lineEdit_30->setEnabled(false);
        lineEdit_30->setGeometry(QRect(30, 180, 31, 20));
        lineEdit_31 = new QLineEdit(groupBox_4);
        lineEdit_31->setObjectName(QStringLiteral("lineEdit_31"));
        lineEdit_31->setEnabled(false);
        lineEdit_31->setGeometry(QRect(30, 240, 31, 20));
        checkBox_29 = new QCheckBox(groupBox_4);
        checkBox_29->setObjectName(QStringLiteral("checkBox_29"));
        checkBox_29->setGeometry(QRect(10, 200, 21, 21));
        lineEdit_32 = new QLineEdit(groupBox_4);
        lineEdit_32->setObjectName(QStringLiteral("lineEdit_32"));
        lineEdit_32->setEnabled(false);
        lineEdit_32->setGeometry(QRect(30, 200, 31, 20));
        checkBox_31 = new QCheckBox(groupBox_4);
        checkBox_31->setObjectName(QStringLiteral("checkBox_31"));
        checkBox_31->setGeometry(QRect(10, 240, 21, 21));
        checkBox_33 = new QCheckBox(groupBox_4);
        checkBox_33->setObjectName(QStringLiteral("checkBox_33"));
        checkBox_33->setGeometry(QRect(10, 180, 21, 21));
        checkBox_34 = new QCheckBox(groupBox_4);
        checkBox_34->setObjectName(QStringLiteral("checkBox_34"));
        checkBox_34->setGeometry(QRect(10, 140, 21, 21));
        checkBox_35 = new QCheckBox(groupBox_4);
        checkBox_35->setObjectName(QStringLiteral("checkBox_35"));
        checkBox_35->setGeometry(QRect(10, 160, 21, 21));
        checkBox_36 = new QCheckBox(groupBox_4);
        checkBox_36->setObjectName(QStringLiteral("checkBox_36"));
        checkBox_36->setGeometry(QRect(10, 220, 21, 21));
        lineEdit_33 = new QLineEdit(groupBox_4);
        lineEdit_33->setObjectName(QStringLiteral("lineEdit_33"));
        lineEdit_33->setEnabled(false);
        lineEdit_33->setGeometry(QRect(30, 140, 31, 20));
        lineEdit_34 = new QLineEdit(groupBox_4);
        lineEdit_34->setObjectName(QStringLiteral("lineEdit_34"));
        lineEdit_34->setEnabled(false);
        lineEdit_34->setGeometry(QRect(30, 160, 31, 20));
        lineEdit_36 = new QLineEdit(groupBox_4);
        lineEdit_36->setObjectName(QStringLiteral("lineEdit_36"));
        lineEdit_36->setEnabled(false);
        lineEdit_36->setGeometry(QRect(30, 260, 31, 20));
        lineEdit_37 = new QLineEdit(groupBox_4);
        lineEdit_37->setObjectName(QStringLiteral("lineEdit_37"));
        lineEdit_37->setEnabled(false);
        lineEdit_37->setGeometry(QRect(30, 340, 31, 20));
        lineEdit_38 = new QLineEdit(groupBox_4);
        lineEdit_38->setObjectName(QStringLiteral("lineEdit_38"));
        lineEdit_38->setEnabled(false);
        lineEdit_38->setGeometry(QRect(30, 280, 31, 20));
        lineEdit_39 = new QLineEdit(groupBox_4);
        lineEdit_39->setObjectName(QStringLiteral("lineEdit_39"));
        lineEdit_39->setEnabled(false);
        lineEdit_39->setGeometry(QRect(30, 360, 31, 20));
        checkBox_38 = new QCheckBox(groupBox_4);
        checkBox_38->setObjectName(QStringLiteral("checkBox_38"));
        checkBox_38->setGeometry(QRect(10, 340, 21, 21));
        checkBox_39 = new QCheckBox(groupBox_4);
        checkBox_39->setObjectName(QStringLiteral("checkBox_39"));
        checkBox_39->setGeometry(QRect(10, 320, 21, 21));
        checkBox_40 = new QCheckBox(groupBox_4);
        checkBox_40->setObjectName(QStringLiteral("checkBox_40"));
        checkBox_40->setGeometry(QRect(10, 280, 21, 21));
        lineEdit_41 = new QLineEdit(groupBox_4);
        lineEdit_41->setObjectName(QStringLiteral("lineEdit_41"));
        lineEdit_41->setEnabled(false);
        lineEdit_41->setGeometry(QRect(30, 300, 31, 20));
        checkBox_41 = new QCheckBox(groupBox_4);
        checkBox_41->setObjectName(QStringLiteral("checkBox_41"));
        checkBox_41->setGeometry(QRect(10, 360, 21, 21));
        checkBox_42 = new QCheckBox(groupBox_4);
        checkBox_42->setObjectName(QStringLiteral("checkBox_42"));
        checkBox_42->setGeometry(QRect(10, 260, 21, 21));
        checkBox_44 = new QCheckBox(groupBox_4);
        checkBox_44->setObjectName(QStringLiteral("checkBox_44"));
        checkBox_44->setGeometry(QRect(10, 300, 21, 21));
        lineEdit_42 = new QLineEdit(groupBox_4);
        lineEdit_42->setObjectName(QStringLiteral("lineEdit_42"));
        lineEdit_42->setEnabled(false);
        lineEdit_42->setGeometry(QRect(30, 320, 31, 20));
        pushButton_17 = new QPushButton(groupBox_4);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(60, 20, 91, 23));
        pushButton_18 = new QPushButton(groupBox_4);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(60, 40, 91, 23));
        pushButton_19 = new QPushButton(groupBox_4);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(60, 60, 91, 23));
        pushButton_20 = new QPushButton(groupBox_4);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(60, 80, 91, 23));
        pushButton_21 = new QPushButton(groupBox_4);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(60, 100, 91, 23));
        pushButton_22 = new QPushButton(groupBox_4);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(60, 120, 91, 23));
        pushButton_23 = new QPushButton(groupBox_4);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(60, 220, 91, 23));
        pushButton_24 = new QPushButton(groupBox_4);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(60, 140, 91, 23));
        pushButton_25 = new QPushButton(groupBox_4);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(60, 180, 91, 23));
        pushButton_26 = new QPushButton(groupBox_4);
        pushButton_26->setObjectName(QStringLiteral("pushButton_26"));
        pushButton_26->setGeometry(QRect(60, 240, 91, 23));
        pushButton_27 = new QPushButton(groupBox_4);
        pushButton_27->setObjectName(QStringLiteral("pushButton_27"));
        pushButton_27->setGeometry(QRect(60, 160, 91, 23));
        pushButton_28 = new QPushButton(groupBox_4);
        pushButton_28->setObjectName(QStringLiteral("pushButton_28"));
        pushButton_28->setGeometry(QRect(60, 200, 91, 23));
        pushButton_29 = new QPushButton(groupBox_4);
        pushButton_29->setObjectName(QStringLiteral("pushButton_29"));
        pushButton_29->setGeometry(QRect(60, 340, 91, 23));
        pushButton_30 = new QPushButton(groupBox_4);
        pushButton_30->setObjectName(QStringLiteral("pushButton_30"));
        pushButton_30->setGeometry(QRect(60, 260, 91, 23));
        pushButton_31 = new QPushButton(groupBox_4);
        pushButton_31->setObjectName(QStringLiteral("pushButton_31"));
        pushButton_31->setGeometry(QRect(60, 300, 91, 23));
        pushButton_32 = new QPushButton(groupBox_4);
        pushButton_32->setObjectName(QStringLiteral("pushButton_32"));
        pushButton_32->setGeometry(QRect(60, 360, 91, 23));
        pushButton_33 = new QPushButton(groupBox_4);
        pushButton_33->setObjectName(QStringLiteral("pushButton_33"));
        pushButton_33->setGeometry(QRect(60, 280, 91, 23));
        pushButton_34 = new QPushButton(groupBox_4);
        pushButton_34->setObjectName(QStringLiteral("pushButton_34"));
        pushButton_34->setGeometry(QRect(60, 320, 91, 23));
        groupBox_5 = new QGroupBox(centralWidget);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(490, 20, 161, 151));
        checkBox_37 = new QCheckBox(groupBox_5);
        checkBox_37->setObjectName(QStringLiteral("checkBox_37"));
        checkBox_37->setGeometry(QRect(10, 20, 21, 21));
        lineEdit_53 = new QLineEdit(groupBox_5);
        lineEdit_53->setObjectName(QStringLiteral("lineEdit_53"));
        lineEdit_53->setEnabled(false);
        lineEdit_53->setGeometry(QRect(30, 20, 31, 20));
        checkBox_43 = new QCheckBox(groupBox_5);
        checkBox_43->setObjectName(QStringLiteral("checkBox_43"));
        checkBox_43->setGeometry(QRect(10, 40, 21, 21));
        lineEdit_54 = new QLineEdit(groupBox_5);
        lineEdit_54->setObjectName(QStringLiteral("lineEdit_54"));
        lineEdit_54->setEnabled(false);
        lineEdit_54->setGeometry(QRect(30, 40, 31, 20));
        checkBox_45 = new QCheckBox(groupBox_5);
        checkBox_45->setObjectName(QStringLiteral("checkBox_45"));
        checkBox_45->setGeometry(QRect(10, 80, 21, 21));
        checkBox_46 = new QCheckBox(groupBox_5);
        checkBox_46->setObjectName(QStringLiteral("checkBox_46"));
        checkBox_46->setGeometry(QRect(10, 60, 21, 21));
        lineEdit_55 = new QLineEdit(groupBox_5);
        lineEdit_55->setObjectName(QStringLiteral("lineEdit_55"));
        lineEdit_55->setEnabled(false);
        lineEdit_55->setGeometry(QRect(30, 60, 31, 20));
        lineEdit_56 = new QLineEdit(groupBox_5);
        lineEdit_56->setObjectName(QStringLiteral("lineEdit_56"));
        lineEdit_56->setEnabled(false);
        lineEdit_56->setGeometry(QRect(30, 80, 31, 20));
        checkBox_47 = new QCheckBox(groupBox_5);
        checkBox_47->setObjectName(QStringLiteral("checkBox_47"));
        checkBox_47->setGeometry(QRect(10, 120, 21, 21));
        checkBox_48 = new QCheckBox(groupBox_5);
        checkBox_48->setObjectName(QStringLiteral("checkBox_48"));
        checkBox_48->setGeometry(QRect(10, 100, 21, 21));
        lineEdit_57 = new QLineEdit(groupBox_5);
        lineEdit_57->setObjectName(QStringLiteral("lineEdit_57"));
        lineEdit_57->setEnabled(false);
        lineEdit_57->setGeometry(QRect(30, 100, 31, 20));
        lineEdit_58 = new QLineEdit(groupBox_5);
        lineEdit_58->setObjectName(QStringLiteral("lineEdit_58"));
        lineEdit_58->setEnabled(false);
        lineEdit_58->setGeometry(QRect(30, 120, 31, 20));
        pushButton_59 = new QPushButton(groupBox_5);
        pushButton_59->setObjectName(QStringLiteral("pushButton_59"));
        pushButton_59->setGeometry(QRect(60, 20, 91, 23));
        pushButton_60 = new QPushButton(groupBox_5);
        pushButton_60->setObjectName(QStringLiteral("pushButton_60"));
        pushButton_60->setGeometry(QRect(60, 40, 91, 23));
        pushButton_61 = new QPushButton(groupBox_5);
        pushButton_61->setObjectName(QStringLiteral("pushButton_61"));
        pushButton_61->setGeometry(QRect(60, 60, 91, 23));
        pushButton_62 = new QPushButton(groupBox_5);
        pushButton_62->setObjectName(QStringLiteral("pushButton_62"));
        pushButton_62->setGeometry(QRect(60, 80, 91, 23));
        pushButton_63 = new QPushButton(groupBox_5);
        pushButton_63->setObjectName(QStringLiteral("pushButton_63"));
        pushButton_63->setGeometry(QRect(60, 100, 91, 23));
        pushButton_64 = new QPushButton(groupBox_5);
        pushButton_64->setObjectName(QStringLiteral("pushButton_64"));
        pushButton_64->setGeometry(QRect(60, 120, 91, 23));
        WizardUI->setCentralWidget(centralWidget);
        groupBox_2->raise();
        groupBox->raise();
        groupBox_3->raise();
        groupBox_4->raise();
        groupBox_5->raise();
        menuBar = new QMenuBar(WizardUI);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1093, 21));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        WizardUI->setMenuBar(menuBar);
        statusBar = new QStatusBar(WizardUI);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        WizardUI->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuFile->addAction(actionSave);
        menuFile->addAction(actionLoad);
        menuFile->addSeparator();
        menuFile->addAction(actionExit);

        retranslateUi(WizardUI);

        QMetaObject::connectSlotsByName(WizardUI);
    } // setupUi

    void retranslateUi(QMainWindow *WizardUI)
    {
        WizardUI->setWindowTitle(QApplication::translate("WizardUI", "WizardUI", 0));
        actionExit->setText(QApplication::translate("WizardUI", "Exit", 0));
        actionSave->setText(QApplication::translate("WizardUI", "Save", 0));
        actionLoad->setText(QApplication::translate("WizardUI", "Load", 0));
        groupBox->setTitle(QApplication::translate("WizardUI", "Available Spell Slots", 0));
        checkBox_32->setText(QApplication::translate("WizardUI", "7", 0));
        checkBox_19->setText(QApplication::translate("WizardUI", "5", 0));
        checkBox_4->setText(QApplication::translate("WizardUI", "1", 0));
        checkBox_18->setText(QApplication::translate("WizardUI", "5", 0));
        checkBox_8->setText(QApplication::translate("WizardUI", "2", 0));
        checkBox_21->setText(QApplication::translate("WizardUI", "10", 0));
        checkBox_16->setText(QApplication::translate("WizardUI", "4", 0));
        checkBox_14->setText(QApplication::translate("WizardUI", "4", 0));
        checkBox_9->setText(QApplication::translate("WizardUI", "7", 0));
        checkBox_15->setText(QApplication::translate("WizardUI", "4", 0));
        checkBox_11->setText(QApplication::translate("WizardUI", "3", 0));
        checkBox_17->setText(QApplication::translate("WizardUI", "8", 0));
        checkBox_2->setText(QApplication::translate("WizardUI", "1", 0));
        checkBox_10->setText(QApplication::translate("WizardUI", "3", 0));
        checkBox_12->setText(QApplication::translate("WizardUI", "3", 0));
        checkBox_7->setText(QApplication::translate("WizardUI", "2", 0));
        checkBox_25->setText(QApplication::translate("WizardUI", "6", 0));
        checkBox_3->setText(QApplication::translate("WizardUI", "1", 0));
        checkBox_13->setText(QApplication::translate("WizardUI", "8", 0));
        checkBox->setText(QApplication::translate("WizardUI", "1", 0));
        checkBox_6->setText(QApplication::translate("WizardUI", "2", 0));
        checkBox_22->setText(QApplication::translate("WizardUI", "9", 0));
        checkBox_20->setText(QApplication::translate("WizardUI", "5", 0));
        checkBox_30->setText(QApplication::translate("WizardUI", "6", 0));
        groupBox_2->setTitle(QApplication::translate("WizardUI", "Player Characteristics", 0));
        label->setText(QApplication::translate("WizardUI", "Level", 0));
        label_2->setText(QApplication::translate("WizardUI", "Class", 0));
        lineEdit_3->setText(QApplication::translate("WizardUI", "1", 0));
        label_3->setText(QApplication::translate("WizardUI", "Background", 0));
        label_4->setText(QApplication::translate("WizardUI", "Race", 0));
        label_5->setText(QApplication::translate("WizardUI", "Character Name", 0));
        label_6->setText(QApplication::translate("WizardUI", "Player Name", 0));
        label_7->setText(QApplication::translate("WizardUI", "Alignment", 0));
        label_8->setText(QApplication::translate("WizardUI", "XP", 0));
        label_9->setText(QApplication::translate("WizardUI", "XP modifier", 0));
        pushButton->setText(QApplication::translate("WizardUI", "+", 0));
        pushButton_2->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_15->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_16->setText(QApplication::translate("WizardUI", "+", 0));
        lineEdit_59->setText(QString());
        label_10->setText(QApplication::translate("WizardUI", "Proficiency Bonus", 0));
        label_11->setText(QApplication::translate("WizardUI", "Inspiration", 0));
        lineEdit_60->setText(QString());
        label_12->setText(QApplication::translate("WizardUI", "Armor Class", 0));
        lineEdit_62->setText(QString());
        pushButton_65->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_66->setText(QApplication::translate("WizardUI", "+", 0));
        lineEdit_63->setText(QString());
        label_13->setText(QApplication::translate("WizardUI", "Modified Armor Class", 0));
        label_14->setText(QApplication::translate("WizardUI", "Initiative", 0));
        lineEdit_61->setText(QString());
        lineEdit_64->setText(QString());
        label_15->setText(QApplication::translate("WizardUI", "Speed", 0));
        pushButton_37->setText(QApplication::translate("WizardUI", "Apply", 0));
        groupBox_3->setTitle(QApplication::translate("WizardUI", "Statistics", 0));
        pushButton_3->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_4->setText(QApplication::translate("WizardUI", "+", 0));
        lineEdit_12->setText(QString());
        pushButton_7->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_8->setText(QApplication::translate("WizardUI", "+", 0));
        lineEdit_15->setText(QString());
        pushButton_9->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_10->setText(QApplication::translate("WizardUI", "+", 0));
        lineEdit_17->setText(QString());
        pushButton_11->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_12->setText(QApplication::translate("WizardUI", "+", 0));
        lineEdit_19->setText(QString());
        pushButton_13->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_14->setText(QApplication::translate("WizardUI", "+", 0));
        lineEdit_21->setText(QString());
        pushButton_36->setText(QApplication::translate("WizardUI", "Intelligence", 0));
        pushButton_38->setText(QApplication::translate("WizardUI", "Wisdom", 0));
        pushButton_39->setText(QApplication::translate("WizardUI", "Dexterity", 0));
        pushButton_40->setText(QApplication::translate("WizardUI", "Constitution", 0));
        pushButton_41->setText(QApplication::translate("WizardUI", "Charisma", 0));
        pushButton_6->setText(QApplication::translate("WizardUI", "+", 0));
        lineEdit_13->setText(QString());
        pushButton_5->setText(QApplication::translate("WizardUI", "-", 0));
        pushButton_35->setText(QApplication::translate("WizardUI", "Strength", 0));
        pushButton_42->setText(QApplication::translate("WizardUI", "Apply", 0));
        groupBox_4->setTitle(QApplication::translate("WizardUI", "Skills", 0));
        checkBox_5->setText(QString());
        lineEdit_23->setText(QString());
        checkBox_23->setText(QString());
        lineEdit_24->setText(QString());
        checkBox_24->setText(QString());
        checkBox_26->setText(QString());
        lineEdit_25->setText(QString());
        lineEdit_26->setText(QString());
        checkBox_27->setText(QString());
        checkBox_28->setText(QString());
        lineEdit_27->setText(QString());
        lineEdit_28->setText(QString());
        lineEdit_29->setText(QString());
        lineEdit_30->setText(QString());
        lineEdit_31->setText(QString());
        checkBox_29->setText(QString());
        lineEdit_32->setText(QString());
        checkBox_31->setText(QString());
        checkBox_33->setText(QString());
        checkBox_34->setText(QString());
        checkBox_35->setText(QString());
        checkBox_36->setText(QString());
        lineEdit_33->setText(QString());
        lineEdit_34->setText(QString());
        lineEdit_36->setText(QString());
        lineEdit_37->setText(QString());
        lineEdit_38->setText(QString());
        lineEdit_39->setText(QString());
        checkBox_38->setText(QString());
        checkBox_39->setText(QString());
        checkBox_40->setText(QString());
        lineEdit_41->setText(QString());
        checkBox_41->setText(QString());
        checkBox_42->setText(QString());
        checkBox_44->setText(QString());
        lineEdit_42->setText(QString());
        pushButton_17->setText(QApplication::translate("WizardUI", "Acrobatics", 0));
        pushButton_18->setText(QApplication::translate("WizardUI", "Animal Handling", 0));
        pushButton_19->setText(QApplication::translate("WizardUI", "Arcana", 0));
        pushButton_20->setText(QApplication::translate("WizardUI", "Athletics", 0));
        pushButton_21->setText(QApplication::translate("WizardUI", "Deception", 0));
        pushButton_22->setText(QApplication::translate("WizardUI", "History", 0));
        pushButton_23->setText(QApplication::translate("WizardUI", "Nature", 0));
        pushButton_24->setText(QApplication::translate("WizardUI", "Insight", 0));
        pushButton_25->setText(QApplication::translate("WizardUI", "Investigation", 0));
        pushButton_26->setText(QApplication::translate("WizardUI", "Perception", 0));
        pushButton_27->setText(QApplication::translate("WizardUI", "Intimidation", 0));
        pushButton_28->setText(QApplication::translate("WizardUI", "Medicine", 0));
        pushButton_29->setText(QApplication::translate("WizardUI", "Stealth", 0));
        pushButton_30->setText(QApplication::translate("WizardUI", "Performance", 0));
        pushButton_31->setText(QApplication::translate("WizardUI", "Religion", 0));
        pushButton_32->setText(QApplication::translate("WizardUI", "Survival", 0));
        pushButton_33->setText(QApplication::translate("WizardUI", "Persuasion", 0));
        pushButton_34->setText(QApplication::translate("WizardUI", "Sleight of Hand", 0));
        groupBox_5->setTitle(QApplication::translate("WizardUI", "Saving Throws", 0));
        checkBox_37->setText(QString());
        lineEdit_53->setText(QString());
        checkBox_43->setText(QString());
        lineEdit_54->setText(QString());
        checkBox_45->setText(QString());
        checkBox_46->setText(QString());
        lineEdit_55->setText(QString());
        lineEdit_56->setText(QString());
        checkBox_47->setText(QString());
        checkBox_48->setText(QString());
        lineEdit_57->setText(QString());
        lineEdit_58->setText(QString());
        pushButton_59->setText(QApplication::translate("WizardUI", "Strength", 0));
        pushButton_60->setText(QApplication::translate("WizardUI", "Dexterity", 0));
        pushButton_61->setText(QApplication::translate("WizardUI", "Constitution", 0));
        pushButton_62->setText(QApplication::translate("WizardUI", "Intelligence", 0));
        pushButton_63->setText(QApplication::translate("WizardUI", "Wisdom", 0));
        pushButton_64->setText(QApplication::translate("WizardUI", "Charisma", 0));
        menuFile->setTitle(QApplication::translate("WizardUI", "File", 0));
    } // retranslateUi

};

namespace Ui {
    class WizardUI: public Ui_WizardUI {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WIZARDUI_H
